### ISSUE TITLE
doc.body replaced after eg app contructor

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-notification#11]
thus attaching to DOM need to move to an 'attached'. seems more work than worth mabye

**Comment by RWOverdijk** [comment]
I don't get it. What does this break?

**Comment by doktordirk** [comment]
humanejs uses 

```
         var el = doc.createElement('div')
         this.container = document.body;
         this.container.appendChild(el)
```

so, if body is replaced by bootstrapper ...

preivously, the body got replaced before app constructor and thus other constructors. that's not ensured anymore. see https://github.com/aurelia/bootstrapper/issues/40 .

**Comment by RWOverdijk** [comment]
Hm but as long as the user does this _after_ construct we should be fine?

**Comment by doktordirk** [comment]
yes

**Comment by doktordirk** [comment]
hence, one option is just to update the readme only

**Comment by RWOverdijk** [comment]
I :+1: that. When we need it we'll build it :) But good to have this documented! :)

**Comment by doktordirk** [comment]
found .DOM.createCustomEvent('aurelia-composed'',... which could be used. .. tomorrow
