### ISSUE TITLE
ts sample

### ISSUE THREAD

**Issue by doktordirk** [SpoonX/aurelia-notification#28]
like the others i have

**Comment by doktordirk** [comment]
made my webpack sample https://github.com/doktordirk/aurelia-notification-sample

ts for i18n doens't ready. so, won't do that now

**Comment by mttmccb** [comment]
trying to get it working for ts and webpack with no joy, hope you manage to get an example working,

**Comment by RWOverdijk** [comment]
@mttmccb Doesn't @doktordirk his example work? If not, a new, working example can be made (will be done anyway).

**Comment by doktordirk** [comment]
my webpacks work fine

**Comment by mttmccb** [comment]
There's no typescript in that example

**Comment by doktordirk** [comment]
ah, yes. had small issue and no time then

**Comment by doktordirk** [comment]
@mttmccb ah. see above : "ts for i18n doens't ready. so, won't do that now"

**Comment by doktordirk** [comment]
if you have a plain ts i18n sample for me i'll try again

**Comment by mttmccb** [comment]
I managed to get i18n working, it's not in a public repo at the moment, I'll post a sample later.

However based on the (painful) experience I've had with Typescript I think I might stick with ES2016 and webpack

**Comment by doktordirk** [comment]
yeah, also having a weird ts issue right now. too much pain for the gain

**Comment by mttmccb** [comment]
Here you go... my [i18n branch](https://github.com/mttmccb/skeleton-navigation/tree/i18n), it's not that far behind the master one, still get an error this (known) error but it works, I remember right just remove the import in this file got rid of it.

```
ERROR in /Users/mttmccb/Projects/aurelia/skeleton-navigation/skeleton-typescriptwebpack/typings/browser/ambient/aurelia-i18n/index.d.ts
(4,23): error TS2307: Cannot find module 'i18next'.
```

Hope it helps.

My current app has aurelia-i18n, aurelia-dialog and aurelia-notification but it's painful to get working with ts and webpack and in fact it doesn't work for inexplicable reasons...

**Comment by doktordirk** [comment]
alright. tx. done
