### ISSUE TITLE
Getting Undefined

### ISSUE THREAD

**Issue by allencoded** [SpoonX/aurelia-notification#34]
Once I call notification.success('success') I am getting the notification but the text instead of success says undefined.

```
import { Notification } from 'aurelia-notification';
@inject(Notification)
export class Welcome {
  constructor(notification) {
    notification.success('success');
    this.message = '';
  }

```

main.js:

```
bootstrap((aurelia) => {
  aurelia.use
  .standardConfiguration()
  .developmentLogging()
  .plugin('aurelia-notification', config => {
    config.configure({
      notifications: {
        'success': 'humane-flatty-success',
        'error': 'humane-flatty-error',
        'info': 'humane-flatty-info'
      }
    });
  });
```

Like I said I am getting it to show the notification box with it styled right. Just the text says undefined.

**Comment by doktordirk** [comment]
i think the usage of aurelia-i18n is mandantory again. was optional for some time, but there had been problems providing both options together. 

here's a simple sample https://github.com/doktordirk/aurelia-notification-sample
atm only ts-jspm and es6-webpack, but it should be close enough to get you going.

else maybe visit us on gitter

**Comment by allencoded** [comment]
I figured it out if I do this:

```
bootstrap((aurelia) => {
  aurelia.use
  .standardConfiguration()
  .developmentLogging()
  .plugin('aurelia-notification', config => {
    config.configure({
      translate: false,
      notifications: {
        success: 'humane-flatty-success',
        error: 'humane-flatty-error',
        info: 'humane-flatty-info',
      },
    });
  });
```

Specify `translate = false` it works.

**Comment by doktordirk** [comment]
ah, so still works. nice. but i guess i should highlight that more in the readme :smile:
