### ISSUE TITLE
Provide base container configuration in plugin config

### ISSUE THREAD

**Issue by apawsey** [SpoonX/aurelia-notification#38]
I would want to set the base notification container globally, when I initialise the plugin, but at the moment, that option isn't available.

Just to note, I intend to submit my first ever public PR for this... so either tell me no now, or go easy on me :)

**Comment by RWOverdijk** [comment]
@apawsey I just checked and I think you're right, it can't be done in configure at the moment (without using container anyway). I think this is a good idea. :)

**Comment by doktordirk** [comment]
Just know that at init time Aurelia will still replace the whole document body (in default setting). So, most likely you would still need to attach your Container later anyways

**Comment by apawsey** [comment]
Yeah but that's a design issue.  I think most people building an actual app with aurelia have moved away from whole body replacement.  The point is, if I have a layout that supports this, it doesn't make sense to have to configure the base container for notifications on a method call much later, than just doing it in the configuration of the plugin.

**Comment by codeflowee** [comment]
Are we expecting any update on this?

**Comment by RWOverdijk** [comment]
@codeflowee I don't think anyone has made a PR for this yet. Want to give it a crack?

**Comment by RWOverdijk** [comment]
@apawsey Or are you still planning on contributing this feature?
