### ISSUE TITLE
Notifications do not disappear, and cannot be clicked (to close) unless you include at least original css classes from humane

### ISSUE THREAD

**Issue by apawsey** [SpoonX/aurelia-notification#39]
If supported, humane relies on css transitions to remove messages.  Therefore if you do not include the minimum necessary classes, the messages never disappear.  As the clickToClose functionality uses the same method to make the notification disappear, it also doesn't work.

**Comment by RWOverdijk** [comment]
That's true. We should mention that somewhere! A getting started would be nice (including the css, too).

I'll keep this issue open until I have time to do that. In case you want to take this on, feel free :)
