### ISSUE TITLE
Must Implement AddPlugin()

### ISSUE THREAD

**Issue by allencoded** [SpoonX/aurelia-notification#46]
Since the latest aurelia build (skeleton) I noticed a weird bug: `aurelia-loader.js:145 Uncaught (in promise) Error: Loader must implement addPlugin(pluginName, implementation).(…)`. This is the JSPM build.

Before the update we never had an issue but I am guessing something changed.

```
import 'jquery';
import bootstrap from 'bootstrap';
import 'humane-js/themes/flatty.css!';

export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('aurelia-notification', config => {
        config.configure({
          translate: false,
          notifications: {
            success: 'humane-flatty-success',
            error: 'humane-flatty-error',
            info: 'humane-flatty-info',
          },
        });
      });
...
```

I went into the skeleton and only installed this to ensure that this was the problematic plugin and it appears that 'aurelia-notification' is the problem child :(

**Comment by doktordirk** [comment]
Try 
If install breaks your application, try resolving jspm forks: 

$ jspm inspect --forks
$ jspm resolve --only registry:package-name@version

E.g. 

$ jspm inspect --forks
     Installed Forks

         npm:aurelia-dependency-injection 1.0.0-beta.1.2.3 1.0.0-beta.2.1.0

$ jspm resolve --only npm:aurelia-dependency-injection@1.0.0-beta.2.1.0

**Comment by allencoded** [comment]
That works thanks
