### ISSUE TITLE
Can't load theme with new version of Aurelia

### ISSUE THREAD

**Issue by rosshigh** [SpoonX/aurelia-notification#55]
I've configured aurelia-notification in aurelia.json using:

```
    {
            "name": "humane-js",
            "path": "../node_modules/humane-js",
            "main": "humane",
            "resources": [
              "themes/bigbox.css",
              "themes/boldlight.css",
              "themes/flatty.css",
              "themes/jackedup.css",
              "themes/libnotify.css",
              "themes/original.css"
            ]
          }
```

This seems to work (at least there are no errors).  However, when I use a statement like this to import a theme:

```
    import "node_modules/humane-js/themes/libnotify.css!";
```

I get this error:

```
   Error: ENOENT: no such file or directory, open 'C:\Development\UCCSS\Gold-uccss\aurelia-app\src\node_modules\humane-js\themes\libnotify.css.js
```

I've tried a number of variations on the import statement but I always get the error that it can't find a *.js file.  I'd appreciate if someone can point me in the right direction.

Ross

**Comment by doktordirk** [comment]
that works for me in the view.html:

``` html
 <require from="humane-js/themes/libnotify.css"></require>
```

**Comment by rosshigh** [comment]
That works.  I was just wondering if I was missing something from the example in the documentation.  I have a utility function that shows notifications and it would feel cleaner to load the theme in the same JavaScript module.

Thanks,
