### ISSUE TITLE
aurelia-cli: error TS1192: Module ''i18next'' has no default export.

### ISSUE THREAD

**Issue by road42** [SpoonX/aurelia-notification#60]
I get an error when `aurelia-notification` typings are included:

```
Finished 'processMarkup'
(...)/node_modules/aurelia-i18n/dist/aurelia-i18n.d.ts(1,8): error TS1192: Module ''i18next'' has no default export.
[13:35:32] gulp-notify: [Error running Gulp] Error: (...)/node_modules/aurelia-i18n/dist/aurelia-i18n.d.ts(1,8): error TS1192: Module ''i18next'' has no default export.
[13:35:32] TypeScript: 1 semantic error
[13:35:32] TypeScript: emit succeeded (with errors)
Finished 'buildTypeScript'
```

When I comment out `import {I18N} from 'aurelia-i18n';` in file `aurelia-notification.d.ts` then `au build` compiles without errors.

**Comment by road42** [comment]
So i changed the first line in `aurelia-i18n.d.ts` from 

`import i18next from 'i18next';`

to 

`import * as i18next from 'i18next';`

The error is gone and everything (notification including translation) works.

**Comment by doktordirk** [comment]
tricky. the d.ts is genarated and the other version is needed for babel in the src js afaik. hmm. i.ll have to test that
