### ISSUE TITLE
Support for i18n parameters

### ISSUE THREAD

**Issue by chabou-san** [SpoonX/aurelia-notification#64]
First of all, let me thank you for your library.

I'd like to see a new feature which should not be too hard, I guess. I'm using Aurelia-i18N to translate my notifications but I can't add parameters to the translations. Currently, this is the way I'm using your library:
```js
this.notification.success('myKey', { user: 'John Doe' });
```

And my translation file is 
```json
{
    "myKey": "Thanks, {{user}}"
}
```

And of course the `user` doesn't get translated due to the way you call [ i18n.tr function](../blob/master/src/notification.js#L186) without `options` parameter. Would you please add support for this ?
BTW, I don't get why you use `this.__i18n` in line 186 and you use `this.i18n` in line 184. Should they be the same ?

**Comment by RWOverdijk** [comment]
Sure! Feel free to submit a PR :)

And yeah, could be. Both work, it's just multiple people working on the same project. As it's pretty small, those details were overlooked.
